# Generated by Django 5.2.7 on 2025-11-04 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Categoría')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('icon', models.CharField(default='fa-gun', max_length=50, verbose_name='Icono Font Awesome')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='weapon',
            name='caliber',
            field=models.CharField(default='5.56x45mm', max_length=50, verbose_name='Calibre'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Disponible'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weapons', to='weapons.category', verbose_name='Categoría'),
        ),
        migrations.CreateModel(
            name='Modification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la Modificación')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('modification_type', models.CharField(choices=[('muzzle', 'Boca de Cañón'), ('stock', 'Culata'), ('grip', 'Empuñadura'), ('sight', 'Mira'), ('magazine', 'Cargador'), ('other', 'Otro')], max_length=50, verbose_name='Tipo de Modificación')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='weapons.weapon', verbose_name='Arma Compatible')),
            ],
            options={
                'verbose_name': 'Modificación',
                'verbose_name_plural': 'Modificaciones',
                'ordering': ['name'],
            },
        ),
    ]
